version: "3.8"
services:
    ccda:
        image: $
        ports: 
            - "8000:8000"
        links:
            - "database"
            - "mcaas_db"
        depends_on: 
            - "database"
            - "mcaas_db"
        env_file:
            - ./env/container.env
        volumes:
            - type: bind
              source: ./ccda
              target: /home/ccda
        command: ["wait-for-it", "database:5432", "--","wait-for-it","mcaas_db:3306","--","bash","/home/boostrap.sh","container"]

    web:
    
    database:
        image: "postgres:latest"
        ports: 
            - "5432:5432"
        env_file:
            - ./env/container.env

    mcaas_db: 
        image: "mysql:5.7"
        ports: 
            - "3306:3306"
        env_file:
            - ./env/container.env
